[project]
name = "ascii-gm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "catppuccin>=2.5.0",
    "colorama>=0.4.6",
    "pillow>=11.0.0",
    "pydantic>=2.9.2",
    "tqdm>=4.66.5",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "ty>=0.0.63",
]

[tool.ruff]
line-length = 120
